[package]
name = "program"
version = "0.1.0"
edition = "2018"

[dependencies]
solana-program = "1.8.5"
borsh = "0.9.1"
borsh-derive = "0.9.1"

[features]
no-entrypoint = []

[dev-dependencies]
solana-program-test = "1.8.5"
solana-sdk = "1.8.5"

[lib]
crate-type = ["cdylib", "lib"]